- name: Install MySQL Database
  apt: name={{ item }} state=present
  with_items:
    - default-mysql-client
    - default-mysql-server
- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install pymysql
  pip:
    name: pymysql
    state: present

- name: Create Application Database
  mysql_db:
    name: '{{ db_name }}'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Database User
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '*.*:ALL'
    state: present
    host: '%'
